version: '3.9'

services:
  skilllearning-api:
    container_name: skilllearning-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: "Host=postgres;Port=5432;Database=SkillLearningDb;Username=postgres;Password=admin;"
      Redis__ConnectionString: redis:6379
      Kafka__BootstrapServers: kafka:9092
      Jwt__Key: /02j+p5N7XgL8Q1rG9tY/2mB4kP7u0xV5cR3zW6a9S0I=
      Jwt__Issuer: http://localhost:5000
      Jwt__Audience: https://localhost:4200
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - skilllearning-net

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: SkillLearningDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - skilllearning-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d SkillLearningDb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 45s
  
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - skilllearning-net

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "8081:5540"
    networks:
      - skilllearning-net
    depends_on:
      - redis

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - skilllearning-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - skilllearning-net

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: skilllearning-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - skilllearning-net

networks:
  skilllearning-net:
    driver: bridge

volumes:
  pgdata:


# docker-compose up -d --build
# dotnet ef migrations add InitialCreate --project SkillLearning.Infrastructure --output-dir Persistence/Migrations
# dotnet ef database update --project SkillLearning.Infrastructure
