name: Update Project Structure Tree

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Backend/**'
      - '.github/workflows/update-structure.yml'

jobs:
  update_tree:
    name: Update Project Structure Tree
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install tree
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Generate and inject project tree
        uses: anmol098/fill-readme-action@main
        with:
          readme_path: "README.md"
          data_source: |
            echo '```'
            tree Backend -L 3 --dirsfirst -I 'bin|obj|.vs|Properties'
            echo '```'
          section_name: "project_tree"
          gh_token: ${{ secrets.GH_PAT }}
          commit_message: "docs: update project structure tree"
