name: Update Project Structure Tree

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Backend/**'

jobs:
  update_tree:
    name: Update Project Structure Tree
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install tree
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Generate project tree
        run: |
          echo '```' > tree.md
          tree Backend -L 3 --dirsfirst -I 'bin|obj|.vs|Properties' >> tree.md
          echo '```' >> tree.md

      - name: Inject tree into README
        uses: anmol098/string-replace-action@v1.3
        with:
          pattern: '[\s\S]*'
          string_to_replace: |
            ${{ steps.read_tree.outputs.file_content }}
            # Arquivo para ler o conteúdo (necessário um passo extra para isso)
          file_path: 'README.md'
          
      - name: Read tree structure file
        id: read_tree
        uses: anmol098/read-file-actions@v1.2
        with:
          path: tree.md

      - name: Update README with project tree
        uses: anmol098/string-replace-action@v1.3
        with:
          path: 'README.md'
          pattern: '[\s\S]*'
          string_to_replace: |
            ${{ steps.read_tree.outputs.file_content }}
            # Passo 6: Fazer o commit das alterações no README.md
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update project structure tree"
          file_pattern: README.md